#!/bin/bash

MODE=$1 # on/off

#
# $ pactl list sink-inputs
#
#   ... application.name   =
#   ... device.description =
#   ... media.name         =
#

APPS=(
    "telegram-desktop"
    "whatsapp-for-linux"
)

if [ "$MODE" == "on" ]; then
    MODE="mute"
    xfconf-query -c xfce4-notifyd -p /do-not-disturb -s true 2>/dev/null
else
    MODE="unmute"
    xfconf-query -c xfce4-notifyd -p /do-not-disturb -s false 2>/dev/null
fi

#for APP in "${APPS[@]}"; do
#    $HOME/bin/toggle-app-audio $APP $MODE
#done