#!/usr/bin/env bash

DEVICE_MAC=$2
DEVICE_MAC_UNDERSCORED=$(echo $DEVICE_MAC | sed 's/:/_/g')

DEVICE_NAME="bluez_card.$DEVICE_MAC_UNDERSCORED"
DEVICE_SINK="bluez_output.$DEVICE_MAC_UNDERSCORED"
DEVICE_SOURCE="bluez_input.$DEVICE_MAC_UNDERSCORED"

HEADSET_PROFILE='headset-head-unit'
SPEAKER_PROFILE_AAC='a2dp-sink-aac'
SPEAKER_PROFILE_SBC='a2dp-sink-sbc'

SPEAKER_SINK='a2dp-sink'
HEADSET_SINK='headset-head-unit'
HEADSET_SOURCE='headset-head-unit'

if [[ -z "$2" ]]; then
  echo "Usage: $0 <connect | disconnect | headset | speaker> [device_mac_address]"
  exit 1
fi

connect() {
  bluetooth on
  sleep 3
  bluetoothctl connect $DEVICE_MAC
  sleep 3
  speaker
}

disconnect() {
  bluetoothctl disconnect $DEVICE_MAC
}

headset() {
  #
  # Controlled by wireplumber
  #
  pactl set-card-profile $DEVICE_NAME $HEADSET_PROFILE
  sleep 1
  pactl set-default-sink $(pactl list sinks short | grep -i "$DEVICE_SINK" | awk '{print $2}')
  pactl set-default-source $(pactl list sources short | grep -i "$DEVICE_SOURCE" | awk '{print $2}')
}

speaker() {
  #
  # Controlled by wireplumber
  #
  pactl set-card-profile $DEVICE_NAME $SPEAKER_PROFILE_AAC
  sleep 1
  pactl set-default-sink $(pactl list sinks short | grep -i "$DEVICE_SINK" | awk '{print $2}')
}

case "$1" in
connect)
  connect
  ;;
disconnect)
  disconnect
  ;;
headset)
  headset
  ;;
speaker)
  speaker
  ;;
esac