# Alacritty Configuration - personalizado

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[colors.normal]
black   = "0x282828"
red     = "0xcc241d"
green   = "0x98971a"
yellow  = "0xd79921"
blue    = "0x458588"
magenta = "0xb16286"
cyan    = "0x689d6a"
white   = "0xa89984"

[colors.bright]
black   = "0x928374"
red     = "0xfb4934"
green   = "0xb8bb26"
yellow  = "0xfabd2f"
blue    = "0x83a598"
magenta = "0xd3869b"
cyan    = "0x8ec07c"
white   = "0xebdbb2"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "Fira Code Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Fira Code Nerd Font"
style = "BoldItalic"

[font.italic]
family = "Fira Code Nerd Font"
style = "Italic"

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "SearchBackward"
key = "F"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 5

[window]
opacity = 0.85
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 15
y = 10
