#!/bin/bash

MUTED_COLOR="#FF6961"
UNMUTED_COLOR="#8BC34A"

RUNNING_DEVICE=$(pactl list short sources |  grep 'RUNNING' | awk '{print $2}')
DEFAULT_DEVICE_NAME=$(pactl get-default-source)
MUTED=$(pactl get-source-mute $DEFAULT_DEVICE_NAME | sed 's/Mute: //g' | uniq)

if [[ $RUNNING_DEVICE =~ 'HD_Pro_Webcam' ]]; then
    DEVICE_ICON="󰖠"
elif [[ $RUNNING_DEVICE =~ 'CalDigit' ]]; then
    DEVICE_ICON="󱂩"
elif [[ $RUNNING_DEVICE =~ 'Headset' ]]; then
    DEVICE_ICON="󰋋"
elif [[ $RUNNING_DEVICE =~ 'HiFi' ]]; then
    DEVICE_ICON=""
elif [[ $RUNNING_DEVICE =~ 'bluez' ]]; then
    DEVICE_ICON="󰋋"
elif [[ $RUNNING_DEVICE =~ 'analog' ]]; then
    DEVICE_ICON=""
elif [[ $RUNNING_DEVICE =~ 'Mic1' ]]; then
    DEVICE_ICON=""
elif [[ $RUNNING_DEVICE =~ 'USB_Audio' ]]; then
    DEVICE_ICON="󰓃"
fi

if [[ $MUTED == "no" ]]; then
    echo "%{F${UNMUTED_COLOR}}$DEVICE_ICON%{F-}"
else
    echo "%{F${MUTED_COLOR}}$DEVICE_ICON%{F-}"
fi